name: Build APK - Problem Solver

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android
      uses: android-actions/setup-android@v3
      
    - name: Fix Common Issues
      run: |
        # إصلاح أذونات الملفات
        chmod +x gradlew 2>/dev/null || echo "No gradlew found"
        
        # إنشاء ملفات مفقودة إذا لزم الأمر
        if [ ! -f "settings.gradle" ] && [ ! -f "settings.gradle.kts" ]; then
          echo "Creating missing settings.gradle"
          echo 'pluginManagement {
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()
            }
          }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories {
                google()
                mavenCentral()
            }
          }
          rootProject.name = "MediaReceiverPro"
          include ":app"' > settings.gradle
        fi
        
        # التحقق من ملفات البناء الأساسية
        if [ ! -f "build.gradle" ] && [ ! -f "build.gradle.kts" ]; then
          echo "❌ ERROR: No build.gradle file found!"
          exit 1
        fi
        
        if [ ! -f "app/build.gradle" ] && [ ! -f "app/build.gradle.kts" ]; then
          echo "❌ ERROR: No app/build.gradle file found!"
          exit 1
        fi
        
    - name: Build APK Step by Step
      run: |
        echo "=== Step 1: Clean Project ==="
        ./gradlew clean --no-daemon || gradle clean --no-daemon
        
        echo "=== Step 2: Check Dependencies ==="
        ./gradlew dependencies --no-daemon || gradle dependencies --no-daemon
        
        echo "=== Step 3: Build APK ==="
        ./gradlew assembleDebug --no-daemon --stacktrace || gradle assembleDebug --no-daemon --stacktrace
        
    - name: Upload Success Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Success-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload Error Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Error-Logs
        path: |
          app/build/reports/
          app/build/outputs/logs/
        retention-days: 7