name: Build APK - Simple

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android
      uses: android-actions/setup-android@v3
      
    - name: Build APK
      run: |
        # تثبيت Gradle يدوياً لتجنب المشاكل
        wget -q https://services.gradle.org/distributions/gradle-8.4-bin.zip
        unzip -q gradle-8.4-bin.zip
        ./gradle-8.4/bin/gradle clean assembleDebug --no-daemon --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-APK
        path: app/build/outputs/apk/debug/app-debug.apk